// Nexus Pop - Official Fandom Merchandise Catalog
// Authentic Launch Edition - Specializing in Anime, Marvel, and DC merchandise

export const FRANCHISES = {
  "jjk": {
    id: "jjk",
    name: "Jujutsu Kaisen",
    character: "Satoru Gojo & Megumi",
    universe: "Anime",
    tagline: "Unlimited Void & Cursed Energy",
    quote: "Throughout heaven and earth, I alone am the honored one.",
    quoteAuthor: "Satoru Gojo",
    banner: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80",
    themeColor: "rose",
    accentGlow: "rgba(244, 63, 94, 0.4)",
    description: "Step into the jujutsu sorcery realm with archival foil art prints, laser-engraved charms, and drop-tested covers designed for true Jujutsu Kaisen enthusiasts.",
    bundle: {
      name: "Gojo Satoru 'Honored One' Ultimate Trio",
      productIds: ["np-001", "np-007", "np-010"],
      originalPrice: 947,
      bundlePrice: 799,
      savings: 148,
      badge: "Save ₹148 with Trio Bundle"
    }
  },
  "spiderman": {
    id: "spiderman",
    name: "Spider-Man: Spider-Verse",
    character: "Miles Morales & Peter Parker",
    universe: "Marvel",
    tagline: "What's Up Danger • Leap of Faith",
    quote: "Anyone can wear the mask. You can wear the mask. If you didn't know that before, I hope you do now.",
    quoteAuthor: "Miles Morales",
    banner: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=1200&q=80",
    themeColor: "cyan",
    accentGlow: "rgba(6, 182, 212, 0.4)",
    description: "Electrifying neon graffiti aesthetics inspired by Into & Across the Spider-Verse. Built for comic connoisseurs and web-heads across India.",
    bundle: {
      name: "Spider-Verse Web-Head Collector Set",
      productIds: ["np-002", "np-008", "np-011"],
      originalPrice: 1097,
      bundlePrice: 899,
      savings: 198,
      badge: "Save ₹198 with Web Bundle"
    }
  },
  "batman": {
    id: "batman",
    name: "The Batman & Gotham",
    character: "The Dark Knight & Arkham Rogues",
    universe: "DC",
    tagline: "I Am The Shadows • Gotham City Noir",
    quote: "Fear is a tool. When that light hits the sky, it's not just a call. It's a warning.",
    quoteAuthor: "The Batman",
    banner: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    themeColor: "purple",
    accentGlow: "rgba(168, 85, 247, 0.4)",
    description: "Rain-slicked asphalt, crimson spot-gloss aesthetics, and heavy-duty armor accessories forged for Gotham's nocturnal protectors.",
    bundle: {
      name: "Gotham Shadows Tactical Vault",
      productIds: ["np-003", "np-006", "np-012"],
      originalPrice: 1247,
      bundlePrice: 999,
      savings: 248,
      badge: "Save ₹248 with Gotham Bundle"
    }
  },
  "demonslayer": {
    id: "demonslayer",
    name: "Demon Slayer: Kimetsu no Yaiba",
    character: "Tanjiro Kamado & Nezuko",
    universe: "Anime",
    tagline: "Hinokami Kagura • Sun Breathing",
    quote: "Set your heart ablaze! Go beyond your limits!",
    quoteAuthor: "Kyojuro Rengoku",
    banner: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=80",
    themeColor: "amber",
    accentGlow: "rgba(245, 158, 11, 0.4)",
    description: "Traditional wave patterns infused with modern drop protection and scratch-resistant acrylic. Forged with the spirit of the Demon Slayer Corps.",
    bundle: {
      name: "Demon Slayer Corps Starter Pack",
      productIds: ["np-004", "np-015", "np-010"],
      originalPrice: 817,
      bundlePrice: 699,
      savings: 118,
      badge: "Save ₹118 with Corps Bundle"
    }
  },
  "onepiece": {
    id: "onepiece",
    name: "One Piece: Gear 5 Sun God",
    character: "Monkey D. Luffy",
    universe: "Anime",
    tagline: "The Drums of Liberation • Sun God Nika",
    quote: "If you don't take risks, you can't create a future!",
    quoteAuthor: "Monkey D. Luffy",
    banner: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
    themeColor: "rose",
    accentGlow: "rgba(244, 63, 94, 0.4)",
    description: "Celebrate Luffy's peak liberation form with 100% waterproof dishwasher-safe vinyl sticker bombs and foil art prints.",
    bundle: {
      name: "Straw Hat Grand Fleet Pack",
      productIds: ["np-010", "np-007", "np-013"],
      originalPrice: 897,
      bundlePrice: 749,
      savings: 148,
      badge: "Save ₹148 with Grand Fleet Bundle"
    }
  }
};

export const PRODUCTS = [
  {
    id: "np-001",
    name: "Jujutsu Kaisen: Gojo Satoru 'Unlimited Void' Premium Foil Poster",
    universe: "Anime",
    franchiseKey: "jjk",
    category: "Posters",
    price: 499,
    originalPrice: 899,
    edition: "Batch #01 (Limited 50 Pcs)",
    launchStatus: "New Drop",
    craftsmanship: "300+ GSM Archival Matte Foil Cardstock",
    badge: "First Edition",
    badgeColor: "rose",
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
    description: "Museum-grade 300 GSM cardstock featuring Satoru Gojo's iconic Domain Expansion with metallic electric-blue foil highlights. UV-protected and glare-free.",
    tags: ["Gojo", "JJK", "Anime", "Domain Expansion", "Poster", "Holographic", "Jujutsu Kaisen"]
  },
  {
    id: "np-002",
    name: "Spider-Man: Miles Morales 'What's Up Danger' Neon Canvas Poster",
    universe: "Marvel",
    franchiseKey: "spiderman",
    category: "Posters",
    price: 549,
    originalPrice: 999,
    edition: "Batch #01 (50 Pcs)",
    launchStatus: "Fresh Arrival",
    craftsmanship: "Textured Matte Canvas with High-Density Inks",
    badge: "Artist Drop",
    badgeColor: "cyan",
    image: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=800&q=80",
    description: "High-contrast inverted leap art inspired by Into the Spider-Verse. Printed on textured matte art canvas with deep vibrant blacks and neon red accents.",
    tags: ["Spider-Man", "Miles Morales", "Marvel", "Spider-Verse", "Poster", "Neon"]
  },
  {
    id: "np-003",
    name: "The Batman (2022): 'I Am The Shadows' Crimson Silhouette Poster",
    universe: "DC",
    franchiseKey: "batman",
    category: "Posters",
    price: 599,
    originalPrice: 1099,
    edition: "Batch #01 (35 Pcs)",
    launchStatus: "Limited Edition",
    craftsmanship: "350 GSM Velvet Board with Crimson Spot Gloss",
    badge: "Collector Drop",
    badgeColor: "purple",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    description: "Moody, rain-soaked Gotham aesthetic printed on velvety 350 GSM matte board. Features subtle crimson spot gloss over the Bat symbol.",
    tags: ["Batman", "DC", "Gotham", "Dark Knight", "Poster", "Noir"]
  },
  {
    id: "np-004",
    name: "Demon Slayer: Tanjiro & Nezuko Hinokami Kagura Shockproof Case",
    universe: "Anime",
    franchiseKey: "demonslayer",
    category: "Phone Covers",
    price: 399,
    originalPrice: 699,
    edition: "Batch #01 (Limited Run)",
    launchStatus: "New Drop",
    craftsmanship: "10ft Drop Armor Dual-Layer TPU & Polycarbonate",
    badge: "Armor Case",
    badgeColor: "amber",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    description: "Military-grade 10ft drop protection with dual-layer TPU and anti-scratch polycarbonate. Fire dragon wave motif with raised camera bezel.",
    tags: ["Demon Slayer", "Tanjiro", "Nezuko", "Anime", "Phone Cover", "Kimetsu"]
  },
  {
    id: "np-005",
    name: "Iron Man: Arc Reactor Mark LXXXV MagSafe Armored Phone Case",
    universe: "Marvel",
    franchiseKey: "ironman",
    category: "Phone Covers",
    price: 499,
    originalPrice: 899,
    edition: "Batch #01",
    launchStatus: "Stark Tech",
    craftsmanship: "Built-in N52 Strong Neodymium MagSafe Magnets",
    badge: "MagSafe Armor",
    badgeColor: "cyan",
    image: "https://images.unsplash.com/photo-1635863138275-d9b33299680b?auto=format&fit=crop&w=800&q=80",
    description: "Engineered with integrated N52 strong neodymium magnets for flawless MagSafe alignment. Metallic gold-titanium brushed finish with luminescent core ring.",
    tags: ["Iron Man", "Tony Stark", "Marvel", "Avengers", "Phone Cover", "MagSafe"]
  },
  {
    id: "np-006",
    name: "The Joker: 'Why So Serious?' Dark Knight Tempered Glass Case",
    universe: "DC",
    franchiseKey: "batman",
    category: "Phone Covers",
    price: 429,
    originalPrice: 799,
    edition: "Batch #01",
    launchStatus: "Cult Classic",
    craftsmanship: "9H Hardness Scratch-Proof Tempered Glass Backplate",
    badge: "Tempered Glass",
    badgeColor: "purple",
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80",
    description: "9H scratch-resistant tempered glass backplate showcasing Heath Ledger's iconic Joker graffiti art with tactile textured grip bumpers.",
    tags: ["Joker", "DC", "Batman", "Dark Knight", "Phone Cover", "Glass"]
  },
  {
    id: "np-007",
    name: "Attack on Titan: Scout Regiment 'Wings of Freedom' Double Acrylic Keychain",
    universe: "Anime",
    franchiseKey: "aot",
    category: "Acrylic Keychains",
    price: 249,
    originalPrice: 399,
    edition: "Batch #01",
    launchStatus: "Vault Drop",
    craftsmanship: "Laser-Cut 4mm Crystal Clear Double Acrylic Charm",
    badge: "Double Layer",
    badgeColor: "rose",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    description: "Laser-cut 4mm thick crystal-clear acrylic with dual-sided print. Fitted with heavy-duty brushed gunmetal swivel clasp and mini blade charm.",
    tags: ["Attack on Titan", "AOT", "Wings of Freedom", "Levi", "Anime", "Keychain"]
  },
  {
    id: "np-008",
    name: "Deadpool & Wolverine: 'Best Bubs Heart Split' Double Acrylic Keychain",
    universe: "Marvel",
    franchiseKey: "spiderman",
    category: "Acrylic Keychains",
    price: 299,
    originalPrice: 499,
    edition: "Batch #01 (Limited)",
    launchStatus: "Duo Set",
    craftsmanship: "Dual Interlocking Acrylic Charms with Holographic Coat",
    badge: "2-Piece Set",
    badgeColor: "cyan",
    image: "https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=800&q=80",
    description: "Interlocking magnetic dual acrylic charm set! Keep one half or gift the other to your favorite chimichanga buddy. Holographic shimmer coat.",
    tags: ["Deadpool", "Wolverine", "Marvel", "Keychain", "Acrylic", "Best Bubs"]
  },
  {
    id: "np-009",
    name: "The Flash: 'Speed Force Lightning' Neon Core Acrylic Keychain",
    universe: "DC",
    franchiseKey: "flash",
    category: "Acrylic Keychains",
    price: 229,
    originalPrice: 379,
    edition: "Batch #01",
    launchStatus: "Neon Core",
    craftsmanship: "Light-Trapping Fluorescent Acrylic with Solid Swivel Ring",
    badge: "Glow Accent",
    badgeColor: "purple",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    description: "Vibrant fluorescent acrylic that naturally catches ambient light with an intense yellow-crimson glow. Weatherproof and scratch-proof.",
    tags: ["Flash", "DC", "Speed Force", "Justice League", "Keychain"]
  },
  {
    id: "np-010",
    name: "One Piece: Gear 5 Luffy 'Sun God Nika' Vinyl Sticker Pack (5-Piece)",
    universe: "Anime",
    franchiseKey: "onepiece",
    category: "Vinyl Stickers",
    price: 199,
    originalPrice: 349,
    edition: "Batch #01",
    launchStatus: "Fan Favorite",
    craftsmanship: "100% Waterproof Heavyweight Vinyl (Dishwasher Safe)",
    badge: "5-Piece Pack",
    badgeColor: "rose",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    description: "Heavyweight 100% waterproof matte vinyl stickers featuring Luffy in Sun God Nika mode. Dishwasher-safe and residue-free removal for laptops and water bottles.",
    tags: ["One Piece", "Luffy", "Gear 5", "Anime", "Stickers", "Waterproof"]
  },
  {
    id: "np-011",
    name: "Avengers: Retro Comic Panel Bomb Vinyl Sticker Pack (10-Piece)",
    universe: "Marvel",
    franchiseKey: "spiderman",
    category: "Vinyl Stickers",
    price: 249,
    originalPrice: 449,
    edition: "Batch #01",
    launchStatus: "Pack Deal",
    craftsmanship: "Anti-Scratch Gloss UV-Laminated Die-Cut Vinyl",
    badge: "10-Piece Pack",
    badgeColor: "cyan",
    image: "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=800&q=80",
    description: "Curated vintage Silver Age comic action cuts featuring Thor, Captain America, Iron Man, Black Widow, and Hulk with glossy UV laminate.",
    tags: ["Avengers", "Marvel", "Comic", "Vintage", "Stickers", "Vinyl"]
  },
  {
    id: "np-012",
    name: "Batman: Arkham Rogues Gallery Matte Vinyl Sticker Pack (8-Piece)",
    universe: "DC",
    franchiseKey: "batman",
    category: "Vinyl Stickers",
    price: 219,
    originalPrice: 399,
    edition: "Batch #01",
    launchStatus: "Rogues Pack",
    craftsmanship: "Outdoor Grade UV Matte Shield Film (Residue-Free)",
    badge: "8-Piece Pack",
    badgeColor: "purple",
    image: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=800&q=80",
    description: "Includes high-definition die-cut emblems of Batman, Nightwing, Red Hood, Joker, Riddler, and Harley Quinn with weatherproof outdoor rating.",
    tags: ["Batman", "DC", "Arkham", "Rogues", "Stickers", "Waterproof"]
  },
  {
    id: "np-013",
    name: "Naruto Shippuden: Itachi Uchiha Mangekyo Sharingan Matte Phone Cover",
    universe: "Anime",
    franchiseKey: "naruto",
    category: "Phone Covers",
    price: 449,
    originalPrice: 799,
    edition: "Batch #01",
    launchStatus: "Akatsuki Drop",
    craftsmanship: "Etched Blood-Red Sharingan with Interior Microfiber",
    badge: "Matte Touch",
    badgeColor: "rose",
    image: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80",
    description: "Deep obsidian matte finish with blood-red etched Sharingan pupil ring. Soft microfiber interior lining to safeguard your phone chassis.",
    tags: ["Naruto", "Itachi", "Sharingan", "Uchiha", "Anime", "Phone Cover"]
  },
  {
    id: "np-014",
    name: "Loki: 'Glorious Purpose' TVA Minimalist Gold Foil Wall Poster",
    universe: "Marvel",
    franchiseKey: "loki",
    category: "Posters",
    price: 529,
    originalPrice: 899,
    edition: "Batch #01",
    launchStatus: "Limited Edition",
    craftsmanship: "Metallic Gold Hot-Stamped Foil on Archival Black Card",
    badge: "Gold Foil",
    badgeColor: "cyan",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
    description: "Official TVA art deco chevron aesthetic rendered with metallic emerald green and gold hot-stamped foil on archival matte stock.",
    tags: ["Loki", "Marvel", "TVA", "Glorious Purpose", "Poster", "Gold Foil"]
  },
  {
    id: "np-015",
    name: "Chainsaw Man: Denji & Pochita Chibi Acrylic Charm Keychain",
    universe: "Anime",
    franchiseKey: "chainsawman",
    category: "Acrylic Keychains",
    price: 219,
    originalPrice: 349,
    edition: "Batch #01",
    launchStatus: "Chibi Cut",
    craftsmanship: "High-Gloss Rounded 3D Candy Epoxy Coating",
    badge: "Epoxy Charm",
    badgeColor: "rose",
    image: "https://images.unsplash.com/photo-1569701813229-33284b643e3c?auto=format&fit=crop&w=800&q=80",
    description: "Super cute chibi art with high-density epoxy coating that gives a rounded, 3D candy effect. Scratch resistant with stainless steel chain.",
    tags: ["Chainsaw Man", "Pochita", "Denji", "Anime", "Keychain", "Acrylic"]
  },
  {
    id: "np-016",
    name: "Superman: 'House of El - Hope' Metropolis Brushed Metal Phone Case",
    universe: "DC",
    franchiseKey: "superman",
    category: "Phone Covers",
    price: 469,
    originalPrice: 799,
    edition: "Batch #01",
    launchStatus: "Steel Shield",
    craftsmanship: "Brushed Aluminum Texture with Honeycomb Shock Dampening",
    badge: "Metal Armor",
    badgeColor: "purple",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    description: "Brushed aluminum-look backplate featuring the Kryptonian glyph for Hope. Shock-absorbing honeycomb internal cushioning.",
    tags: ["Superman", "DC", "House of El", "Man of Steel", "Phone Cover"]
  }
];

if (typeof window !== "undefined") {
  window.NEXUS_PRODUCTS = PRODUCTS;
  window.NEXUS_FRANCHISES = FRANCHISES;
}
if (typeof globalThis !== "undefined") {
  globalThis.NEXUS_PRODUCTS = PRODUCTS;
  globalThis.NEXUS_FRANCHISES = FRANCHISES;
}

export default PRODUCTS;
